// declaring action types

const ADD_FAVOURITE = "ADD_FAVOURITE";
const DEL_FAVOURITE = "DEL_FAVOURITE";
const TOGGLE_SETTING = "TOGGLE_SETTING";
const APP_FOLDER_NAME = '/';

export { ADD_FAVOURITE, DEL_FAVOURITE, TOGGLE_SETTING, APP_FOLDER_NAME };
